name: lint

# Especifica en qué ramas se ejecutará el workflow
on:
  pull_request:
    branches: [main, develop]
#  push:
#    branches:
#      - '**'
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint