
name: Mi primera GitHub actions

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: 'Hello World'
      run: echo "Hello World"
    - name: 'Listado de ficheros'
      run: ls -la