# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test befoer integrate in Develop branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: 'Hello World'
      run: echo "Hello World"
    - name: 'Listado de ficheros'
      run: ls -la
