name: Blank Workflow

# Especifica en qué ramas se ejecutará el workflow
on:
  push:
    branches:
      - '**'

jobs:
  blank-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: List repository content
        run: ls -la

      - name: Mostrar rama actual
        run: git branch --show-current
