name: Blank Workflow

# Especifica en qué ramas se ejecutará el workflow
on:
  push:
    branches:
      - feature/addTestsTargets

jobs:
  blank-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"
