name: Test Before PR to develop

# Especifica en qué ramas se ejecutará el workflow
on:
  push:
    branches:
      - '**'

jobs:
  blank-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"